apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: netty-secure-chat
  annotations:
    description: An example Netty application using SNI and TCP
    tags: instant-app,java
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: netty-secure-chat
    name: netty-secure-chat
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: netty-secure-chat
    name: netty-secure-chat
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: netty-secure-chat:latest
    resources: {}
    source:
      git:
        uri: https://github.com/cpitman/ose-netty-secure-chat-demo.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:latest
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: 23040748b49630af
      type: Generic
    - github:
        secret: 4bb953c6ad56c30f
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: netty-secure-chat
    name: netty-secure-chat
  spec:
    replicas: 1
    selector:
      deploymentconfig: netty-secure-chat
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: netty-secure-chat
          deploymentconfig: netty-secure-chat
      spec:
        containers:
        - env:
          - name: PATH
            value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/s2i
          - name: JAVA_HOME
            value: /usr/lib/jvm/java
          - name: MAVEN_VERSION
            value: 3.3.3
          - name: JOLOKIA_VERSION
            value: 1.3.2
          - name: HAWTAPP_VERSION
            value: 2.2.53
          - name: AB_JOLOKIA_CONFIG
            value: /opt/jolokia/jolokia.properties
          - name: AB_JOLOKIA_AUTH_OPENSHIFT
            value: "true"
          image: netty-secure-chat:latest
          imagePullPolicy: Always
          name: netty-secure-chat
          ports:
          - containerPort: 8992
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - netty-secure-chat
        from:
          kind: ImageStreamTag
          name: netty-secure-chat:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: netty-secure-chat
    name: netty-secure-chat
  spec:
    ports:
    - name: 8992-tcp
      port: 8992
      protocol: TCP
      targetPort: 8992
    selector:
      deploymentconfig: netty-secure-chat
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: netty-secure-chat
    name: netty-secure-chat
  spec:
    port:
      targetPort: 8992-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: netty-secure-chat
